version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:8-jdk
        auth:
          username: $DOCKER_HUB_USER_NAME
          password: $DOCKER_HUB_PASSWORD

    steps:
      - checkout

      - run: gradle dependencies

      - run: ./gradlew build

  deploy:
    docker:
      - image: openjdk:8-jdk
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  version: 2
  workflow:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test